// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'export-pdfs-copying'
  | 'export-pdfs-done'
  | 'export-pdfs-error'
  | 'export-pdfs-no-collection'
  | 'export-pdfs-no-pdfs'
  | 'export-pdfs-pick-folder'
  | 'export-pdfs-start'
  | 'menuitem-export-collection-pdfs'
  | 'menuitem-export-selected-pdfs'
  | 'pref-enable'
  | 'pref-filename-format-title'
  | 'pref-format-author-year-title'
  | 'pref-format-bbt'
  | 'pref-format-bbt-title'
  | 'pref-format-bibtex'
  | 'pref-format-bibtex-title'
  | 'pref-format-custom'
  | 'pref-format-help'
  | 'pref-format-year-title'
  | 'pref-help'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish';
