// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "exportPdfPath": string;
      "exportPdfRecursive": boolean;
      "filenameFormat": string;
      "filenameCustomTemplate": string;
      "apiEnabled": boolean;
      "apiKey": string;
      "apiMaxBatchSize": number;
    };
  }
}
